export enum IncidentStatus {
  CREATED = 'CREATED',
  DISPATCHING = 'DISPATCHING',
  ASSIGNED = 'ASSIGNED',
  ACKNOWLEDGED = 'ACKNOWLEDGED',
  EN_ROUTE = 'EN_ROUTE',
  ARRIVED = 'ARRIVED',
  RESOLVED = 'RESOLVED',
  CANCELLED = 'CANCELLED',
  FALSE_ALARM = 'FALSE_ALARM',
  ESCALATED = 'ESCALATED',
}
